jasypt:
  encryptor:
    password: hello
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sportsgeekdb
#    username: root
#    password: ENC(QRWFXH2r6PfEQmr/WPB1Gw==)
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://mysql-47802-0.cloudclusters.net:18936/sportsgeekdb
#    username: ENC(xwGAuFlhPIZgRVGPeNAJlw==)
#    password: ENC(MOofLqPHPH6tFL1xTbvOXycacmummo1X)
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # To connect from localhost
#  datasource:
#    url: jdbc:postgres://ec2-54-81-126-150.compute-1.amazonaws.com:5432/d8qgprvb42vck1
#    username: byptbshshocrii
#    password: d8a8409d4bd09c28ed55ab557c3b8e6bc33343ef3f43ff3abf0491172df80ff1
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
#    username: sportsgeek.info@gmail.com
    username: sportsgeek.alerts@gmail.com
    password: ENC(jtgUkGZLn5sHz8UgrZxft2wp4IyKQxouPRVN07zxP5w=)
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true

server:
  port: 8080